[[redirects]]
  from = "/api/auth/*"
  to   = "https://zasfwsehtworhyyer.onrender.com/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to   = "https://zasfwsehtworhyyer.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
