services:
  - type: web
    name: bot-fly
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: supersecreto
