services:
  - type: web
    name: bot-fly-api
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerfilePath: infra/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://botflyzap.netlify.app
      - key: DATA_DIR
        value: /srv/data
    disks:
      - name: data
        mountPath: /srv/data
        sizeGB: 1
